### PR TITLE
chore: set up auto-publish to docker on new tag

### PR DESCRIPTION
**Pull request by rchl**
@aaronshaf could you set up the docker tokens?

### CODE REVIEW

**Comment by aaronshaf** [comment]
Apologies, I may need some hand-holding here. Can you point me in the right direction?

**Comment by rchl** [comment]
So in https://github.com/aaronshaf/dynamodb-admin/settings/secrets/actions you would have to add repository secrets:
 - `DOCKERHUB_USERNAME` with value `aaronshaf`
 - `DOCKERHUB_TOKEN` with a token generated at https://hub.docker.com/settings/security

**Comment by aaronshaf** [comment]
Done. Thanks much for all you do.

**Comment by rchl** [comment]
And since I have your attention... :)

- Can you remove all the weird tags (like `dependabot_npm_and_yarn_aws-sdk-2.952.0`) at https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags ?

- Disable CircleCI testing at https://app.circleci.com/settings/project/github/aaronshaf/dynamodb-admin ?

I don't have much time to do much with repo either but just want to clean up a little. :)

**Comment by aaronshaf** [comment]
Yessir, on it!

**Comment by rchl** [comment]
Also, the readme at dockerhub has a badge for CircleCI that could also be removed to not scare people off. :)
https://hub.docker.com/r/aaronshaf/dynamodb-admin

**Comment by rchl** [comment]
All looks good thanks. Will now check if publishing works.

**Comment by aaronshaf** [comment]
Error: buildx failed with: error: invalid tag
"***/dynamodb-admin:${GITHUB_REF/refs\\/tags\\/v/}": invalid reference
format

**Comment by rchl** [comment]
Pushed some extra fixes to master. Now it's saying:

> error: failed to solve: authorization status: 401: authorization failed
> Error: buildx failed with: error: failed to solve: authorization status: 401: authorization failed

https://github.com/aaronshaf/dynamodb-admin/runs/5042668425?check_suite_focus=true

I'm not sure what's up with that, assuming that token is correct...

Also, the description in https://hub.docker.com/r/aaronshaf/dynamodb-admin/tags still has the CircleCI. I don't think it will be synced with GitHub automatically.

**Comment by rchl** [comment]
Maybe the generated token doesn't have a `Write` scope?

**Comment by aaronshaf** [comment]
OK, try now.

**Pull request merged**
