### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jcdesignweb**
fix "purge table" when it try to make a delete all and the table has more one of keys.

### CODE REVIEW

**Comment by rchl** [comment]
This pull request doesn't look correct. You should rebase your changes on latest master branch.

And check if the fix is still needed.

**Comment by rchl** [comment]
Or I guess the problem is that it's set to merge to develop while it should merge to master.

**Comment by jcdesignweb** [comment]
Hi Rafal, I worked in develop branch.. but develop was outdated, therefore
I did merge from master to develop and then I did the changes.But if you
want to refuse the pull request no problem! I try to help to comunity.

Good day.

cheers!

**Comment by rchl** [comment]
I'm glad you made the change, I'm just saying that it shows all the commits unrelated to your change so:
a) it's harder to review
b) It's not possible to merge automatically as the changes should be merged to master, not develop

All I'm asking is for you to drop this PR and submit it again against `master` branch this time.

**Pull request closed without merging**
