### PR TITLE
Ace editor support when editing item

### LINKED ISSUE #11: Use some editor to highlight JSON syntax
Would be nice if there was some syntax highlight when editing JSON data.
What about [Ace](https://ace.c9.io/) ?
I can work on a PR if there are interest on this

### PR DESCRIPTION
**Pull request by MatheusVellone**
- Added bower as a npm dependency
- Added `postinstall` script to install bower dependencies
- Then configured the JSON edit field to be the ace editor instance

Closes #11

### CODE REVIEW

**Comment by MatheusVellone** [comment]
@aaronshaf ?

**Comment by aaronshaf** [comment]
Thank you!

**Comment by MatheusVellone** [comment]
:)
Can you publish a new version to `npm` also ?

**Comment by aaronshaf** [comment]
Sure thing, will do so right now. THANK YOU again for your PR!

**Comment by aaronshaf** [comment]
Done.

**Pull request merged**
